roles = [
        "Kasir",
        "Sales Associate",
        "Manajer",
        "Asisten Manajer Toko",
        "Visual Merchandiser",
        "Customer Service Representative",
        "Marketing",
        "IT Support"
]
kategori = [
    "Elektronik",
    "Fashion",
    "Kecantikan dan Perawatan Pribadi",
    "Makanan dan Minuman",
    "Rumah dan Taman",
    "Olahraga dan Kesehatan",
    "Hobi dan Mainan",
    "Otomotif",
    "Elektronik Rumah Tangga",
    "Perlengkapan Kantor",
    "Perhiasan",
    "Tas",
    "Sepatu",
    "Pakaian Wanita",
    "Pakaian Pria",
    "Kosmetik",
    "Alat-alat Taman",
    "Produk Makanan Organik",
    "Wine dan Minuman Keras",
    "Peralatan Olahrag"
]
provinces = [
    "Aceh",
    "Sumatera Utara",
    "Sumatera Barat",
    "Riau",
    "Kepulauan Riau",
    "Jambi",
    "Bengkulu",
    "Sumatera Selatan",
    "Bangka Belitung",
    "Lampung",
    "Banten",
    "DKI Jakarta",
    "Jawa Barat",
    "Jawa Tengah",
    "DI Yogyakarta",
    "Jawa Timur",
    "Bali",
    "Nusa Tenggara Barat",
    "Nusa Tenggara Timur",
    "Kalimantan Barat",
    "Kalimantan Tengah",
    "Kalimantan Selatan",
    "Kalimantan Timur",
    "Kalimantan Utara",
    "Sulawesi Utara",
    "Gorontalo",
    "Sulawesi Tengah",
    "Sulawesi Barat",
    "Sulawesi Selatan",
    "Sulawesi Tenggara",
    "Maluku",
    "Maluku Utara",
    "Papua Barat",
    "Papua"
]
capitals = [
    "Banda Aceh",
    "Medan",
    "Padang",
    "Pekanbaru",
    "Tanjung Pinang",
    "Jambi",
    "Bengkulu",
    "Palembang",
    "Pangkal Pinang",
    "Bandar Lampung",
    "Serang",
    "Jakarta",
    "Bandung",
    "Semarang",
    "Yogyakarta",
    "Surabaya",
    "Denpasar",
    "Mataram",
    "Kupang",
    "Pontianak",
    "Palangkaraya",
    "Banjarmasin",
    "Samarinda",
    "Tanjung Selor",
    "Manado",
    "Gorontalo",
    "Palu",
    "Mamuju",
    "Makassar",
    "Kendari",
    "Ambon",
    "Sofifi",
    "Manokwari",
    "Jayapura"
]
city = [
    {"city": "Jakarta", "province":"DKI Jakarta" },
    {"city": "Surabaya", "province":"Jawa Timur" },
    {"city": "Bandung", "province":"Jawa Barat" },
    {"city": "Medan", "province":"Sumatera Utara" },
    {"city": "Semarang", "province":"Jawa Tengah" },
    {"city": "Palembang", "province":"Sumatera Selatan" },
    {"city": "Makassar", "province":"Sulawesi Selatan" },
    {"city": "Depok", "province":"Jawa Barat" },
    {"city": "Bekasi", "province":"Jawa Barat" },
    {"city": "Tangerang", "province":"Banten" },
    {"city": "Bogor", "province":"Jawa Barat" },
    {"city": "Malang", "province":"Jawa Timur" },
    {"city": "Yogyakarta", "province":"DI Yogyakarta" },
    {"city": "Batam", "province":"Kepulauan Riau" },
    {"city": "Pekanbaru", "province":"Riau" },
    {"city": "Balikpapan", "province":"Kalimantan Timur" },
    {"city": "Samarinda", "province":"Kalimantan Timur" },
    {"city": "Padang", "province":"Sumatera Barat" },
    {"city": "Banjarmasin", "province":"Kalimantan Selatan" },
    {"city": "Pontianak", "province":"Kalimantan Barat" },
    {"city": "Manado", "province":"Sulawesi Utara" },
    {"city": "Denpasar", "province":"Bali" },
    {"city": "Bandar Lampung", "province":"Lampung" },
    {"city": "Jambi", "province":"Jambi" },
    {"city": "Surakarta", "province":"Jawa Tengah" },
    {"city": "Ambon", "province":"Maluku" },
    {"city": "Palu", "province":"Sulawesi Tengah" },
    {"city": "Kendari", "province":"Sulawesi Tenggara" },
    {"city": "Gorontalo", "province":"Gorontalo" },
    {"city": "Mataram", "province":"Nusa Tenggara Barat" },
    {"city": "Tomohon", "province":"Sulawesi Utara" },
    {"city": "Bitung", "province":"Sulawesi Utara" },
    {"city": "Kotamobagu", "province":"Sulawesi Utara" },
    {"city": "Luwuk", "province":"Sulawesi Tengah" },
    {"city": "Bau-Bau", "province":"Sulawesi Tenggara" },
    {"city": "Tual", "province":"Maluku" },
    {"city": "Serui", "province":"Papua" },
    {"city": "Merauke", "province":"Papua" },
    {"city": "Timika", "province":"Papua" },
    {"city": "Sorong", "province":"Papua Barat" },
    {"city": "Nabire", "province":"Papua" },
    {"city": "Jayapura", "province":"Papua" },
    {"city": "Biak", "province":"Papua" },
    {"city": "Manokwari", "province":"Papua Barat" },
    {"city": "Fakfak", "province":"Papua Barat" },
    {"city": "Bima", "province":"Nusa Tenggara Barat" },
    {"city": "Dompu", "province":"Nusa Tenggara Barat" },
    {"city": "Sumbawa Besar", "province":"Nusa Tenggara Barat" },
    {"city": "Praya", "province":"Nusa Tenggara Barat" },
    {"city": "Selong", "province":"Nusa Tenggara Barat" },
    {"city": "Waingapu", "province":"Nusa Tenggara Timur" },
    {"city": "Ruteng", "province":"Nusa Tenggara Timur" },
    {"city": "Ende", "province":"Nusa Tenggara Timur" },
    {"city": "Maumere", "province":"Nusa Tenggara Timur" },
    {"city": "Larantuka", "province":"Nusa Tenggara Timur" },
    {"city": "Kefamenanu", "province":"Nusa Tenggara Timur" },
    {"city": "Atambua", "province":"Nusa Tenggara Timur" },
    {"city": "Singkawang", "province":"Kalimantan Barat" },
    {"city": "Tarakan", "province":"Kalimantan Utara" },
    {"city": "Palangkaraya", "province":"Kalimantan Tengah" },
    {"city": "Banjarbaru", "province":"Kalimantan Selatan" },
    {"city": "Kotamobagu", "province":"Sulawesi Utara" },
    {"city": "Tanjungbalai", "province":"Sumatera Utara" },
    {"city": "Tebingtinggi", "province":"Sumatera Utara" },
    {"city": "Pematangsiantar", "province":"Sumatera Utara" },
    {"city": "Binjai", "province":"Sumatera Utara" },
    {"city": "Gunungsitoli", "province":"Sumatera Utara" },
    {"city": "Telukdalam", "province":"Sumatera Utara" },
    {"city": "Padangsidempuan", "province":"Sumatera Utara" },
    {"city": "Rantau Prapat", "province":"Sumatera Utara" }
]
















