roles = [
        "Kasir",
        "Sales Associate",
        "Manajer",
        "Asisten Manajer",
        "Visual Merchandiser",
        "Customer Service",
        "Marketing",
        "IT Support"
]

kategori = [
    "Pakaian Pria",
    "Pakaian Wanita",
    "Pakaian Anak-Anak",
    "Sepatu",
    "Aksesoris Fashion",
    "Tas dan Koper",
    "Perhiasan",
    "Jam Tangan",
    "Elektronik",
    "Ponsel dan Aksesoris",
    "Kamera",
    "Perangkat Rumah Tangga",
    "Elektronik Rumah Tangga",
    "Peralatan Dapur",
    "Alat Masak",
    "Peralatan Makan",
    "Peralatan Minum",
    "Alat Pembersih",
    "Perawatan Pribadi",
    "Produk Kecantikan",
    "Produk Perawatan Kulit",
    "Produk Rambut",
    "Kesehatan dan Kecantikan",
    "Obat-obatan",
    "Suplemen",
    "Perawatan Kesehatan",
    "Alat Olahraga",
    "Pakaian Olahraga",
    "Sepatu Olahraga",
    "Perlengkapan Outdoor",
    "Alat Camping",
    "Perhiasan Emas",
    "Perhiasan Perak",
    "Perhiasan Berlian",
    "Perhiasan Batu Mulia",
    "Perhiasan Imitasi",
    "Kado",
    "Bunga",
    "Barang Antik",
    "Mainan Anak",
    "Alat Musik",
    "Alat Musik Gitar",
    "Alat Musik Piano",
    "Alat Musik Drum",
    "Alat Musik Biola",
    "Alat Musik Flute",
    "Alat Musik Saxophone",
    "Alat Musik Keyboard",
    "Alat Musik Vokal",
    "Perangko dan Koleksi Filateli",
    "Seni Lukis",
    "Seni Kerajinan Tangan",
    "Barang-barang Vintage",
    "Film dan Musik",
    "CD Musik",
    "DVD Film",
    "Buku",
    "Buku Fiksi",
    "Buku Non-Fiksi",
    "Buku Anak-Anak",
    "Buku Pelajaran",
    "Majalah",
    "Alat Tulis",
    "Buku Catatan",
    "Buku Jurnal",
    "Alat Gambar",
    "Alat Seni Rupa",
    "Lukisan",
    "Patung",
    "Karya Seni Digital",
    "Keramik",
    "Barang-barang Rumah",
    "Perabotan",
    "Perlengkapan Kamar Tidur",
    "Perlengkapan Kamar Mandi",
    "Perlengkapan Dapur",
    "Perlengkapan Ruang Makan",
    "Perlengkapan Ruang Tamu",
    "Dekorasi Rumah",
    "Lainnya",
    "Alat-alat Perbaikan Rumah",
    "Alat Pertukangan",
    "Alat Taman",
    "Tanaman Hias",
    "Perlengkapan Hewan Peliharaan",
    "Makanan Hewan Peliharaan",
    "Mainan Hewan Peliharaan",
    "Perlengkapan Aquarium",
    "Perabotan Kantor",
    "Perlengkapan Pekerjaan",
    "Perlengkapan Sekolah",
    "Alat Tulis Kantor",
    "Alat Kantor",
    "Peralatan Komputer",
    "Laptop",
    "Desktop PC",
    "Printer",
    "Monitor",
    "Mouse dan Keyboard",
    "Perangkat Lunak",
    "Peralatan Elektronik",
    "Kabel dan Pengisi Daya",
    "Audio dan Headphone",
    "Alat Elektronik DIY",
    "Komponen Elektronik",
    "Perlengkapan Desain Grafis",
    "Perangkat Desain Interior",
    "Perlengkapan Fotografi",
    "Perlengkapan Studio",
    "Alat Perkakas",
    "Alat Ukur",
    "Alat Pemotong",
    "Alat Bor",
    "Peralatan Listrik",
    "Peralatan Mesin",
    "Alat Las",
    "Peralatan Penyimpanan",
    "Rak dan Penyimpanan",
    "Peti Penyimpanan",
    "Kotak Penyimpanan",
    "Peralatan Pembersih",
    "Peralatan Cuci",
    "Peralatan Pelipat",
    "Peralatan Pengering",
    "Peralatan Kecil",
    "Blender dan Mixer",
    "Mesin Kopi",
    "Alat Pembuat Roti",
    "Peralatan Memasak",
    "Peralatan Pemanggang",
    "Peralatan Pembuat Kue",
    "Peralatan Dapur Khusus",
    "Peralatan Memanggang",
    "Peralatan Bar",
    "Alat Penyeduh Teh dan Kopi",
    "Botol Minuman",
    "Cangkir dan Gelas",
    "Peralatan Minuman",
    "Peralatan Wine",
    "Peralatan Barbecue",
    "Peralatan Piknik",
    "Peralatan Camping",
    "Peralatan Pancing",
    "Alat Olahraga Air",
    "Perlengkapan Bersepeda",
    "Peralatan Mendaki",
    "Perlengkapan Mendaki Gunung",
    "Perlengkapan Ski",
    "Peralatan Panjat Tebing",
    "Peralatan Renang",
    "Alat Pancing",
    "Peralatan Selam",
    "Alat Panahan",
    "Peralatan Polo Air",
    "Peralatan Tenis",
    "Alat Golf",
    "Alat Badminton",
    "Peralatan Olahraga Lainnya",
    "Peralatan Pertukangan Kayu",
    "Peralatan Pertukangan Logam",
    "Peralatan Pertukangan Beton",
    "Peralatan Pertukangan Listrik",
    "Peralatan Pertukangan Tangan",
    "Peralatan Pertukangan Otomotif",
    "Peralatan Pertukangan Kayu",
    "Peralatan Pertukangan Logam",
    "Peralatan Pertukangan Beton",
    "Peralatan Pertukangan Listrik",
    "Peralatan Pertukangan Tangan",
    "Peralatan Pertukangan Otomotif",
    "Peralatan Pertukangan Khusus",
    "Peralatan Pertukangan Serbaguna",
    "Peralatan Pertukangan Berkualitas",
    "Peralatan Pertukangan Profesional",
    "Peralatan Pertukangan Pemula",
    "Peralatan Pertukangan DIY",
    "Peralatan Taman",
    "Alat Penanam",
    "Peralatan Penyiraman",
    "Alat Potong Rumput",
    "Alat Kebun",
    "Alat Cangkul",
    "Alat Bajak",
    "Peralatan Penanam",
    "Peralatan Penyiraman",
    "Alat Potong Rumput",
    "Alat Kebun",
    "Alat Cangkul",
    "Alat Bajak",
    "Perlengkapan Hewan Peliharaan",
    "Makanan Hewan Peliharaan",
    "Mainan Hewan Peliharaan",
    "Perlengkapan Aquarium",
    "Makanan Ikan",
    "Perawatan Ikan",
    "Perlengkapan Reptil",
    "Makanan Reptil",
    "Perawatan Reptil",
    "Perlengkapan Kucing",
    "Makanan Kucing",
    "Mainan Kucing",
    "Perlengkapan Anjing",
    "Makanan Anjing",
    "Mainan Anjing",
    "Perlengkapan Burung",
    "Makanan Burung",
    "Perlengkapan Kuda",
    "Makanan Kuda",
    "Perlengkapan Kecil",
    "Perlengkapan Hamster",
    "Perlengkapan Kelinci",
    "Perlengkapan Hamster",
    "Perlengkapan Kelinci",
    "Perlengkapan Ular",
    "Perlengkapan Iguana",
    "Perlengkapan Kura-Kura",
    "Perlengkapan Kadal",
    "Perlengkapan Kura-Kura",
    "Perlengkapan Kadal",
    "Perlengkapan Penyu",
    "Perlengkapan Amfibi",
    "Perlengkapan Kura-Kura",
    "Perlengkapan Kadal",
    "Perlengkapan Penyu",
    "Perlengkapan Amfibi",
    "Perlengkapan Kura-Kura",
    "Perlengkapan Kadal",
    "Perlengkapan Penyu",
    "Perlengkapan Amfibi",
    "Perlengkapan Kura-Kura",
    "Perlengkapan Kadal",
    "Perlengkapan Penyu",
    "Perlengkapan Amfibi",
    "Peralatan Kantor",
    "Perlengkapan Pekerjaan",
    "Perlengkapan Sekolah",
    "Alat Tulis Kantor",
    "Alat Kantor",
    "Peralatan Komputer",
    "Laptop",
    "Desktop PC",
    "Printer",
    "Monitor",
    "Mouse dan Keyboard",
    "Perangkat Lunak",
    "Peralatan Elektronik",
    "Kabel dan Pengisi Daya",
    "Audio dan Headphone",
    "Alat Elektronik DIY",
    "Komponen Elektronik",
    "Perlengkapan Desain Grafis",
    "Perangkat Desain Interior",
    "Perlengkapan Fotografi",
    "Perlengkapan Studio",
    "Alat Perkakas",
    "Alat Ukur",
    "Alat Pemotong",
    "Alat Bor",
    "Peralatan Listrik",
    "Peralatan Mesin",
    "Alat Las",
    "Peralatan Penyimpanan",
    "Rak dan Penyimpanan",
    "Peti Penyimpanan",
    "Kotak Penyimpanan",
    "Peralatan Pembersih",
    "Peralatan Cuci",
    "Peralatan Pelipat",
    "Peralatan Pengering",
    "Peralatan Kecil",
    "Blender dan Mixer",
    "Mesin Kopi",
    "Alat Pembuat Roti",
    "Peralatan Memasak",
    "Peralatan Pemanggang",
    "Peralatan Pembuat Kue",
    "Peralatan Dapur",
    "Peralatan Memanggang",
    "Peralatan Bar",
    "Alat Penyeduh Teh dan Kopi",
    "Botol Minuman",
    "Cangkir dan Gelas",
    "Peralatan Minuman",
    "Peralatan Wine",
    "Peralatan Barbecue",
    "Peralatan Piknik",
    "Peralatan Camping",
    "Peralatan Pancing",
    "Alat Olahraga Air",
    "Perlengkapan Bersepeda",
    "Peralatan Mendaki",
    "Perlengkapan Mendaki Gunung",
    "Perlengkapan Ski",
    "Peralatan Panjat Tebing",
    "Peralatan Renang",
    "Alat Pancing",
    "Peralatan Selam",
    "Alat Panahan",
    "Peralatan Polo Air",
    "Peralatan Tenis",
    "Alat Golf",
    "Alat Badminton",
    "Peralatan Olahraga Lainnya",
    "Peralatan Pertukangan Kayu",
    "Peralatan Pertukangan Logam",
    "Peralatan Pertukangan Beton",
    "Peralatan Pertukangan Listrik",
    "Peralatan Pertukangan Tangan",
    "Peralatan Pertukangan Otomotif",
    "Peralatan Pertukangan Khusus",
    "Peralatan Pertukangan Serbaguna",
    "Peralatan Pertukangan Berkualitas",
    "Peralatan Pertukangan Profesional",
    "Peralatan Pertukangan Pemula",
    "Peralatan Pertukangan DIY",
    "Peralatan Taman",
    "Alat Penanam",
    "Peralatan Penyiraman",
    "Alat Potong Rumput",
    "Alat Kebun",
    "Alat Cangkul",
    "Alat Bajak",
    "Peralatan Penanam",
    "Peralatan Penyiraman",
    "Alat Potong Rumput",
    "Alat Kebun",
    "Alat Cangkul",
    "Alat Bajak",
    "Perlengkapan Hewan Peliharaan",
    "Makanan Hewan Peliharaan",
    "Mainan Hewan Peliharaan",
    "Perlengkapan Aquarium",
    "Makanan Ikan",
    "Perawatan Ikan",
    "Perlengkapan Reptil",
    "Makanan Reptil",
    "Perawatan Reptil",
    "Perlengkapan Kucing",
    "Makanan Kucing",
    "Mainan Kucing",
    "Perlengkapan Anjing",
    "Makanan Anjing",
    "Mainan Anjing",
    "Perlengkapan Burung",
    "Makanan Burung",
    "Perlengkapan Kuda",
    "Makanan Kuda",
    "Perlengkapan Kecil",
    "Perlengkapan Hamster",
    "Perlengkapan Kelinci",
    "Perlengkapan Hamster",
    "Perlengkapan Kelinci",
    "Perlengkapan Ular",
    "Perlengkapan Iguana",
    "Perlengkapan Kura-Kura",
    "Perlengkapan Kadal",
    "Perlengkapan Penyu",
    "Perlengkapan Amfibi",
    "Perlengkapan Kura-Kura",
    "Perlengkapan Kadal",
    "Perlengkapan Penyu",
    "Perlengkapan Amfibi",
    "Perlengkapan Kura-Kura",
    "Perlengkapan Kadal",
    "Perlengkapan Penyu",
    "Perlengkapan Amfibi",
    "Perlengkapan Kura-Kura",
    "Perlengkapan Kadal",
    "Perlengkapan Penyu",
    "Perlengkapan Amfibi",
    "Pakaian Pria",
    "Pakaian Wanita",
    "Pakaian Anak-Anak",
    "Sepatu",
    "Aksesoris Fashion",
    "Tas dan Koper",
    "Perhiasan",
    "Jam Tangan",
    "Elektronik",
    "Ponsel dan Aksesoris",
    "Kamera",
    "Perangkat Rumah Tangga",
    "Elektronik Rumah Tangga",
    "Peralatan Dapur",
    "Alat Masak",
    "Peralatan Makan",
    "Peralatan Minum",
    "Alat Pembersih",
    "Perawatan Pribadi",
    "Produk Kecantikan",
    "Produk Perawatan Kulit",
    "Produk Rambut",
    "Kesehatan dan Kecantikan",
    "Obat-obatan",
    "Suplemen",
    "Perawatan Kesehatan",
    "Alat Olahraga",
    "Pakaian Olahraga",
    "Sepatu Olahraga",
    "Perlengkapan Outdoor",
    "Alat Camping",
    "Perhiasan Emas",
    "Perhiasan Perak",
    "Perhiasan Berlian",
    "Perhiasan Batu Mulia",
    "Perhiasan Imitasi",
    "Kado",
    "Bunga",
    "Barang Antik",
    "Mainan Anak",
    "Alat Musik",
    "Alat Musik Gitar",
    "Alat Musik Piano",
    "Alat Musik Drum",
    "Alat Musik Biola",
    "Alat Musik Flute",
    "Alat Musik Saxophone",
    "Alat Musik Keyboard",
    "Alat Musik Vokal",
    "Perangko dan Koleksi Filateli",
    "Seni Lukis",
    "Seni Kerajinan Tangan",
    "Barang-barang Vintage",
    "Film dan Musik",
    "CD Musik",
    "DVD Film",
    "Buku",
    "Buku Fiksi",
    "Buku Non-Fiksi",
    "Buku Anak-Anak",
    "Buku Pelajaran",
    "Majalah",
    "Alat Tulis",
    "Buku Catatan",
    "Buku Jurnal",
    "Alat Gambar",
    "Alat Seni Rupa",
    "Lukisan",
    "Patung",
    "Karya Seni Digital",
    "Keramik",
    "Barang-barang Rumah",
    "Perabotan",
    "Perlengkapan Kamar Tidur",
    "Perlengkapan Kamar Mandi",
    "Perlengkapan Dapur",
    "Perlengkapan Ruang Makan",
    "Perlengkapan Ruang Tamu",
    "Dekorasi Rumah",
    "Lainnya",
    "Alat-alat Perbaikan Rumah",
    "Alat Pertukangan",
    "Alat Taman",
    "Tanaman Hias",
    "Perlengkapan Hewan Peliharaan",
    "Makanan Hewan Peliharaan",
    "Mainan Hewan Peliharaan",
    "Perlengkapan Aquarium",
    "Perabotan Kantor",
    "Perlengkapan Pekerjaan",
    "Perlengkapan Sekolah",
    "Alat Tulis Kantor",
    "Alat Kantor",
    "Peralatan Komputer",
    "Laptop",
    "Desktop PC",
    "Printer",
    "Monitor",
    "Mouse dan Keyboard",
    "Perangkat Lunak",
    "Peralatan Elektronik",
    "Kabel dan Pengisi Daya",
    "Audio dan Headphone",
    "Alat Elektronik DIY",
    "Komponen Elektronik",
    "Perlengkapan Desain Grafis",
    "Perangkat Desain Interior",
    "Perlengkapan Fotografi",
    "Perlengkapan Studio",
    "Alat Perkakas",
    "Alat Ukur",
    "Alat Pemotong",
    "Alat Bor",
    "Peralatan Listrik",
    "Peralatan Mesin",
    "Alat Las",
    "Peralatan Penyimpanan",
    "Rak dan Penyimpanan",
    "Peti Penyimpanan",
    "Kotak Penyimpanan",
    "Peralatan Pembersih",
    "Peralatan Cuci",
    "Peralatan Pelipat",
    "Peralatan Pengering",
    "Peralatan Kecil",
    "Blender dan Mixer",
    "Mesin Kopi",
    "Alat Pembuat Roti",
    "Peralatan Memasak",
    "Peralatan Pemanggang",
]

provinces = [
    "Aceh",
    "Sumatera Utara",
    "Sumatera Barat",
    "Riau",
    "Kepulauan Riau",
    "Jambi",
    "Bengkulu",
    "Sumatera Selatan",
    "Bangka Belitung",
    "Lampung",
    "Banten",
    "DKI Jakarta",
    "Jawa Barat",
    "Jawa Tengah",
    "DI Yogyakarta",
    "Jawa Timur",
    "Bali",
    "Nusa Tenggara Barat",
    "Nusa Tenggara Timur",
    "Kalimantan Barat",
    "Kalimantan Tengah",
    "Kalimantan Selatan",
    "Kalimantan Timur",
    "Kalimantan Utara",
    "Sulawesi Utara",
    "Gorontalo",
    "Sulawesi Tengah",
    "Sulawesi Barat",
    "Sulawesi Selatan",
    "Sulawesi Tenggara",
    "Maluku",
    "Maluku Utara",
    "Papua Barat",
    "Papua"
]
capitals = [
    "Banda Aceh",
    "Medan",
    "Padang",
    "Pekanbaru",
    "Tanjung Pinang",
    "Jambi",
    "Bengkulu",
    "Palembang",
    "Pangkal Pinang",
    "Bandar Lampung",
    "Serang",
    "Jakarta",
    "Bandung",
    "Semarang",
    "Yogyakarta",
    "Surabaya",
    "Denpasar",
    "Mataram",
    "Kupang",
    "Pontianak",
    "Palangkaraya",
    "Banjarmasin",
    "Samarinda",
    "Tanjung Selor",
    "Manado",
    "Gorontalo",
    "Palu",
    "Mamuju",
    "Makassar",
    "Kendari",
    "Ambon",
    "Sofifi",
    "Manokwari",
    "Jayapura"
]
city = [
    {"city": "Jakarta", "province":"DKI Jakarta" },
    {"city": "Surabaya", "province":"Jawa Timur" },
    {"city": "Bandung", "province":"Jawa Barat" },
    {"city": "Medan", "province":"Sumatera Utara" },
    {"city": "Semarang", "province":"Jawa Tengah" },
    {"city": "Palembang", "province":"Sumatera Selatan" },
    {"city": "Makassar", "province":"Sulawesi Selatan" },
    {"city": "Depok", "province":"Jawa Barat" },
    {"city": "Bekasi", "province":"Jawa Barat" },
    {"city": "Tangerang", "province":"Banten" },
    {"city": "Bogor", "province":"Jawa Barat" },
    {"city": "Malang", "province":"Jawa Timur" },
    {"city": "Yogyakarta", "province":"DI Yogyakarta" },
    {"city": "Batam", "province":"Kepulauan Riau" },
    {"city": "Pekanbaru", "province":"Riau" },
    {"city": "Balikpapan", "province":"Kalimantan Timur" },
    {"city": "Samarinda", "province":"Kalimantan Timur" },
    {"city": "Padang", "province":"Sumatera Barat" },
    {"city": "Banjarmasin", "province":"Kalimantan Selatan" },
    {"city": "Pontianak", "province":"Kalimantan Barat" },
    {"city": "Manado", "province":"Sulawesi Utara" },
    {"city": "Denpasar", "province":"Bali" },
    {"city": "Bandar Lampung", "province":"Lampung" },
    {"city": "Jambi", "province":"Jambi" },
    {"city": "Surakarta", "province":"Jawa Tengah" },
    {"city": "Ambon", "province":"Maluku" },
    {"city": "Palu", "province":"Sulawesi Tengah" },
    {"city": "Kendari", "province":"Sulawesi Tenggara" },
    {"city": "Gorontalo", "province":"Gorontalo" },
    {"city": "Mataram", "province":"Nusa Tenggara Barat" },
    {"city": "Tomohon", "province":"Sulawesi Utara" },
    {"city": "Bitung", "province":"Sulawesi Utara" },
    {"city": "Kotamobagu", "province":"Sulawesi Utara" },
    {"city": "Luwuk", "province":"Sulawesi Tengah" },
    {"city": "Bau-Bau", "province":"Sulawesi Tenggara" },
    {"city": "Tual", "province":"Maluku" },
    {"city": "Serui", "province":"Papua" },
    {"city": "Merauke", "province":"Papua" },
    {"city": "Timika", "province":"Papua" },
    {"city": "Sorong", "province":"Papua Barat" },
    {"city": "Nabire", "province":"Papua" },
    {"city": "Jayapura", "province":"Papua" },
    {"city": "Biak", "province":"Papua" },
    {"city": "Manokwari", "province":"Papua Barat" },
    {"city": "Fakfak", "province":"Papua Barat" },
    {"city": "Bima", "province":"Nusa Tenggara Barat" },
    {"city": "Dompu", "province":"Nusa Tenggara Barat" },
    {"city": "Sumbawa Besar", "province":"Nusa Tenggara Barat" },
    {"city": "Praya", "province":"Nusa Tenggara Barat" },
    {"city": "Selong", "province":"Nusa Tenggara Barat" },
    {"city": "Waingapu", "province":"Nusa Tenggara Timur" },
    {"city": "Ruteng", "province":"Nusa Tenggara Timur" },
    {"city": "Ende", "province":"Nusa Tenggara Timur" },
    {"city": "Maumere", "province":"Nusa Tenggara Timur" },
    {"city": "Larantuka", "province":"Nusa Tenggara Timur" },
    {"city": "Kefamenanu", "province":"Nusa Tenggara Timur" },
    {"city": "Atambua", "province":"Nusa Tenggara Timur" },
    {"city": "Singkawang", "province":"Kalimantan Barat" },
    {"city": "Tarakan", "province":"Kalimantan Utara" },
    {"city": "Palangkaraya", "province":"Kalimantan Tengah" },
    {"city": "Banjarbaru", "province":"Kalimantan Selatan" },
    {"city": "Kotamobagu", "province":"Sulawesi Utara" },
    {"city": "Tanjungbalai", "province":"Sumatera Utara" },
    {"city": "Tebingtinggi", "province":"Sumatera Utara" },
    {"city": "Pematangsiantar", "province":"Sumatera Utara" },
    {"city": "Binjai", "province":"Sumatera Utara" },
    {"city": "Gunungsitoli", "province":"Sumatera Utara" },
    {"city": "Telukdalam", "province":"Sumatera Utara" },
    {"city": "Padangsidempuan", "province":"Sumatera Utara" },
    {"city": "Rantau Prapat", "province":"Sumatera Utara" }
]
payment_method = [
    {
        "nama": "Kartu Kredit", 
        "jenis": [
            "Mandiri","BCA","BNI","BRI","Danamon","CIMB Niaga","Permata","Mega", "BPD", "BPD", "BSI", "Bukopin", "Taspen", "Syariah Mandiri", "Muamalat",
            "UOB","OCBC","Maybank","Panin","Artha Graha Internasional","Woori","Sinarmas","Commonwealth","JTrust","Mayapada","BNP","Mizuho","Sumitomo",
            "Bank Jawa Barat dan Banten Syariah",
            "Bank Jawa Timur Syariah",
            "Bank Sulawesi Selatan dan Sulawesi  Barat Syariah",
            "Bank Kalimantan Barat Syariah",
            "Bank Kalimantan Timur dan Kalimantan Utara ",
            "Bank Sumatra Utara Syariah",
            "Bank Aceh Syariah",
            "Bank Lampung Syariah",
            "Bank Jambi Syariah",
            "Bank Bengkulu Syariah",
            "Bank Sumatera Selatan dan Bangka Belitung Syariah",
            "Bank Riau Syariah"                              
        ]
    },
    {
        "nama": "Transfer Bank",
        "jenis": [
            "Mandiri","BCA","BNI","BRI","Danamon","CIMB Niaga","Permata","Mega", "BPD", "BPD", "BSI", "Bukopin", "Taspen", "Syariah Mandiri", "Muamalat",
            "UOB","OCBC","Maybank","Panin","Artha Graha Internasional","Woori","Sinarmas","Commonwealth","JTrust","Mayapada","BNP","Mizuho","Sumitomo",
            "Bank Jawa Barat dan Banten Syariah",
            "Bank Jawa Timur Syariah",
            "Bank Sulawesi Selatan dan Sulawesi  Barat Syariah",
            "Bank Kalimantan Barat Syariah",
            "Bank Kalimantan Timur dan Kalimantan Utara ",
            "Bank Sumatra Utara Syariah",
            "Bank Aceh Syariah",
            "Bank Lampung Syariah",
            "Bank Jambi Syariah",
            "Bank Bengkulu Syariah",
            "Bank Sumatera Selatan dan Bangka Belitung Syariah",
            "Bank Riau Syariah"
        ]
    },
    {
        "nama": "Dompet Elektronik",
        "jenis": ["GoPay","OVO","DANA","GrabPay","ShopeePay","PayPal", "LinkAja", "Sakuku", "T-Cash", "Jenius Pay", "OCTOPAY"]
    },
    {
        "nama": "Mobile Banking",
        "jenis": ["Mandiri","BCA","BNI","BRI","Danamon","CIMB Niaga","Permata","Mega"]
    },
    {
        "nama": "cash",
        "jenis": ["rupiah", "dolar", "ringgit"]
    },
]

    















